<?php

namespace App\Models;

use Exception;
use Illuminate\Contracts\Filesystem\FileNotFoundException;
use Illuminate\Contracts\Filesystem\Filesystem;
use Illuminate\Support\Facades\Storage;

trait Model
{

}

class Singleton
{
    private static $instance = null;

    public static function getInstance()
    {
        if (is_null(static::$instance))
            static::$instance = new self;
        return static::$instance;
    }

    public function __construct()
    {
    }


}

class Type1 extends Singleton {
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }
}
